apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:+QIKNAUIGB90t/WRWVJujq2mQEciTgLZ,iv:IFQbhU8YBj/rMwHqOYzWnkAJ1W1Zj3JYsM0PwkvZdwE=,tag:ZfY+7Y9hBEYlMqIBccwwRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zu6n8h3re0ftq59w5ajp32xjz60m98q69eygqmp6v54hmrt289dqad9txh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveE9LNCszSzRhWVVmZTUv
            Z3VPRUZzZkFCaFJ6bi9NbFRzSWNZVGVCU1ZjClNlNERhRTZrdjcwai8vOWp5eHNa
            UDBjUHRGc3pSNEVkZTNRa2pwdTJGdUkKLS0tIEdFOUNMU3V5WkNQc0R4amFXWmd0
            Rzd0MEdZNFdLYUxFNERIbERsUW9BSDQK0s3icJAdrV2yreLrR+Xn2y57mqNviQm7
            U47yqrKy6kT8HBsCGrGv4l+lKhlKQDcFUhWDxviNwEgJtYzIgV3C3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T22:09:42Z"
    mac: ENC[AES256_GCM,data:1lL5sEU7vJkiWS+dX3qC8ISqyK9+4pD+KfLHbdDvUJrn4U1YOjeY7FRftMGjUV+g79HAgNpWP5sMC7hunw8sU58nK221rXHmcnJ9wCmOVQIUDRxbnyagxh933sJvFEdez8LvAY0JAf7DjfgrJSnJoN2YeE2IG8+FqY0sfo4DBnc=,iv:oyu5GYgATvmfG/BuZW6048HGzEfXTNgnvQ2x8zUBZQU=,tag:g+hUVHCpXJ024psZlZwbZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
