apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:4kX91FcTa00S9lrrT9rQB3jQo2KNl0BCcaRfcHrxIqEwFqj0VCHtMQ==,iv:8UoPXG+J0R41OH9vKYl25U384rcHR99KyNZQmesUsX8=,tag:EeVjAxnVuRLLu3iKBtmeyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zu6n8h3re0ftq59w5ajp32xjz60m98q69eygqmp6v54hmrt289dqad9txh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBla3RSUTVFSk1QNU1zOEFL
            TWxpbHgveUlLUmVMM3NjcE1ZU0N1ZlVzWkhRCm00TE9SMmFxbkVJRXNvcHlwZnln
            bXFua0x6T2JwNHFCeDlFeGZUbmh2NTQKLS0tIDBPbEcyQzd2ODE1d21jcEozTHJm
            UnJpcDNsREY0QjZkUDFiQUlSUzUvc3MK2xw5EKbJI2ft10FgxkTamMfxSmiv2eYh
            QgqIlNq84nXaWvDcwIcjZzQb08u2nPGk4DUDE2ya7CK8QNxIS+/30A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T21:29:08Z"
    mac: ENC[AES256_GCM,data:yW+8Gt4QiP7EVWy2bcnh5dkL5I9dIV2a0+MuC93kRRfGnXTO85pTj7zwPae6R7dT9F0vLzia1+S+ceZWpPDBjDwaLRk4ZmdHhwSeUm3qMg6kLaWiyPsaxx6vS7InDMq/MLt1dGs37aq7uty5+2co+r5bdC0g+xmM7/0fvcdk/Hs=,iv:Wly2qGVy73gj27cZFhemHr4yIxa4O/oVpX6Xzf6HtpA=,tag:uuQip54snt3CimdAAQbFpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
