apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:j4Dl3vEQyyXeUw3tWd62si3xwaYgJ65RKfjJx1iJnJpgGWaZBN8Ung==,iv:rVyWqw3VyB3zsMy+wfGANjslmIxciudGfCk+qTxPSYo=,tag:ConSKiUc/ofEOd8Hd/JAYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zu6n8h3re0ftq59w5ajp32xjz60m98q69eygqmp6v54hmrt289dqad9txh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRUVCS083RVBCRnlXTG0x
            S0pISFYzQkpVOGVTMkhkVFpvaUQrOGlXL1UwCmNLZkQ5YnVuTHQwYmNGdDZqbStM
            MFNFcG00b3dkTjdHUWxOVS9CRTFBQlkKLS0tIDBKeTBDNERWTUFJSXZJMTFNWDJG
            VFlITFQ4ZDZrN0RsMDFaT1FQUFpaN1kKr9TA5npDO2E4BqgxO0p8fhzPwIe9sonV
            e3uTFIX5vWdjUp1606GO6dF4QPPaFAtJSqAoMSgpcNgwZJTJ+I/a8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T16:15:32Z"
    mac: ENC[AES256_GCM,data:u9d5SfvskXKBcYppMRLNgjxvXtfaPHWHrxubuuCz6clBWKShtxuCmCTN1yPm1/mqCAEV1bMWzbp4OSmgM6QN+ro7dc4GZJoEynXj060i7yt05LEwvna4Jgn7xplr68XmJ7bQfY7FhDupj471shj+SVx/lLfSbHRKA9pLJY4JQuA=,iv:8Np1sqAkOdTNLoy2/FppLxFX07S54rZemZ9yCLP472M=,tag:rAPoP8LXDG6H310cOwrgOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
