apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:2Hote9MhDpkvV5LNer3rLwIeMg+rTryrg1J2PKid3P2OUcswyeyN+w==,iv:6AC7Ty3B0hoj94x5g7DV4ZF99buWWzKX1E7xZuAGIRg=,tag:AHucGQMDWTfy1EPevDDC3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zu6n8h3re0ftq59w5ajp32xjz60m98q69eygqmp6v54hmrt289dqad9txh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeGtrOS84ZSswajUxMVBL
            Z1FnLzNIOHpxOUcxd0tkZStyZm9ydkJPV2tjClpLRnBpVGN1alBGelYrTlREYmF2
            QThSOTUyS3FRaElGTE84Q0N2a1ZSdG8KLS0tIFdKM0E5aHYyZjNuQTJMRFArNWgr
            aW5ibXp1eEFmandLS0Zaa3V5b1J4K2cKZlCfzBhF9Xzh7NyQLqZOlBQmQL8+8IVC
            4f2QTWEfaCngMnP4na0ysA0dTOxdrlNpvdtQgDT0aV/ccxHPJE9D/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T22:09:42Z"
    mac: ENC[AES256_GCM,data:XWZSnxP/tv+XJ0NqCFQ7ZMMu6H2tgJzsCVVhCY8b4Ex8crwfF5PLd1M+Ytf7u0ybRT2Vkw++tpWqkLsLSvFhGVEUveGBznkT0gWUYogRsv0kqS7R5IJKrvc5UBTfrRUcHG7eojHy/+k0XLCCHSB0HD4HB8/2g2HIxwVyZIzOlHc=,iv:fePIEiiRa3QJHeQ/XWeE2eNB9Njx8s92/hYLkaG68Zo=,tag:/miW/89fi5QBhghf+lKE7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
