apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:lAvkPgDcjlV08z0n,iv:p4qAV3YFxUD+bCl9H+exZoeegonMUeT7FP2p+Hk4jAI=,tag:/BG9Pvhbly9E+SF/ZUI/nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zu6n8h3re0ftq59w5ajp32xjz60m98q69eygqmp6v54hmrt289dqad9txh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkL29lZEZTSndITVVucEZP
            b2srRWhWQlhiNXFJaTVLVVdIeU1UV05vTzBFCmpWc1JyTUpGSnJrNDcyRVU5ODRh
            c2x3RkRnamQ0QUFMRVJZMVFnK0ZkZWMKLS0tIEVOdFIvc1hveEhCTTNTMW43MGFI
            bnE1VGdjVEMybXRyTEJLRkpQR0RmTWsKJpFg9Rr4LtoenbhfsWe4vxBapGpjvc6d
            LiGcREkIyKFEUQ8NQhuhHFNBET8S+eBdwQI8Zw/0j9fqLZ7LWLjkgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T22:09:41Z"
    mac: ENC[AES256_GCM,data:8tu5hs7BOJD+QQYAx4rirMDpYnU5OtRejLonW4qQrmOYRVCHsSEe2izX5suHJvbv/S0kKLryCnTfroBCxtMtvPYNoMULEAf6PYw9KyRHLsaeZGxnrubMfLswikQNYzkc4m/k+yD1I1HXUCapIzCzHeys1ylUOqZZ+KrsWrkWXIo=,iv:wDq6ta0p45GbRhaHxjb8AeWf0+5QxpyEx0XpsqlnlM4=,tag:f+qfrBl0XGMGTrYoDsDe1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
