apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:F5Ra0yL59ptPMrMI,iv:yKARx9mhSUUQVzICKQ/i6gXbkLVQ+CN8xhPapL+0uNI=,tag:2rG+wzc+ufKItO3KuBqrpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zu6n8h3re0ftq59w5ajp32xjz60m98q69eygqmp6v54hmrt289dqad9txh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQK05ub3RMOUd1M0RUU0hy
            Tys0bDBZV282SHdKcURwTGkxVDhkZXZSOHhJCll4MGdqRGo0WENGL1R5WCt5RXdS
            OHlxSE1LNHNqRkhQMmlUZHZaV20rODgKLS0tIDkxK1hyaDB0SmJLWVlxcVQwRS9U
            Skl4bXpINUFZNCt6T1lSWk1iRTBRSXMKNzkBVU8Zrb5qHpawquBVwquCtyPbkjR0
            GBGLAf+QflDBePpAM2hLeC5JuJlWZJPCy0l8+cTiqOuVM6YzCOaqYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T21:29:06Z"
    mac: ENC[AES256_GCM,data:e6A++/wqExbcNu3KJSe+CbQ1LIlIb8usmMBXw4ZBwyxVbPtRds2YmAswraVaoqLcJNDbr/L/8IKukDS64fSu2vGVFAeq2CfCpf1i1bM9ZoAYjTgBOisdAdik0+IWhJ0gHfcIpE02DjJ2Az97bZHQ0PrL2Po70GAKE9wgLtYoDWs=,iv:OSRdnSK8t74DXJ+OzDLM/tCQBMmeB9m2oFFjY81N3zs=,tag:R5K+3EE3mPXdCdwww6QxCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
