apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:1UekUb6KUxrg+9upJETZjQt54WFhS7H68ToBmqQtV2tGw5VX,iv:SpQNkU2qxN7PRURXSj9Iogw6Kn1umHSkXzFrKa9176M=,tag:7H4tN2ZOjQJo6MGIEe98xA==,type:str]
    credentials.json: ENC[AES256_GCM,data:+2lrF5d8hNuTOhkkU36HYM0J7hoVNoF8iS7z8nQk7J8Udu3nk8Ja0NXkEo/Dsyc267DVdr4J7/nNkU3brQPtD5jmClIxpYcjCSbzLz1t8pAbh/FQWXkHadtfmihHpnINJiF50gqnPTHzXvlUh89Oj6S7WIJdjqlxBrlXOtzNMWtgy66fqwKjD9dT6Ou7pKKg5cPDIHX+pr3eZgVjqYooWGPmCMkzXjUCDLfRZi4TSA==,iv:PjxdRYks/gy5zReYKgxVZTYC3EmVddkKJHskapu5qX0=,tag:aHi32ILDOecP3kbzL4IXFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zu6n8h3re0ftq59w5ajp32xjz60m98q69eygqmp6v54hmrt289dqad9txh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueERVanB2c2Ewc2pRdlRB
            SVoyYjd3RVJHU0VlOUMrRTFNdWxIT1VVNm5FCkpvcFBpRU9XYzRMZ1V6V2xkMjd4
            ZDhLa2lRbTFBSkdIZ0NRbWh1TkdCSGsKLS0tIHl3Q2NBMURlL2g4dEU1VzlRMnh5
            ZmRPK2dJcmViNFo5MGt5SVh6bExVUXcKdlznqEgQoRKo0YjCJJHEBa5EW4S0Fd15
            fNmSeea9jstNbHjnXSzhTGDcWoP7ypnachfh4r4Zs599MRg8CDUCfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T21:29:07Z"
    mac: ENC[AES256_GCM,data:pPCxyW+/CXisD4eFKRTh+yb5ZDR6O05mLo40bKge0m6M0Px4vSQOWsDtSSTISPpVR1iFarfYp9xjDFykOgvc5Lb6qLsYgEiSqrEAGQXW6UG5A5czsGSEChpyPp3ML1o2azllYlXOlgFXIiQTw8Exqmiwok5+OzkViWxUZhnR1fk=,iv:U+taYoD4jZ8I9hQo5tVujCuf4VM0mqUaEDz4ObPF1kY=,tag:VPFJROn8bBFK6obKAuFoGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
