apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Vnzk1DlFIBeYNlXgzFtreAwPB1mezAv+BG7iOck+HJs8Qc+r,iv:rCKsbaZugq+i1ponBF0VWelO8vkgEPWMZFhR2Xk853A=,tag:Uq4GbL5O+1KhMOoWnOZA8Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:LTnk7fVpQHlN4F6cuL29ppXU7nC69jfOnQlxRqycXrK0zXey4tYysMMrlDTJYEabSWu2JvBSWsUX0CFQiEhTbHxaNxV8m0n/Y9VTjkpzX2bPVk+U3yCkNSV+BooORn9jC4J6+qKHmmbjKvLmxt6uJYCbCERAyNc6vF8+lkYkbeOKtci+wF2FlpERSyYZ2ha85EMqgzntYziwemZRfXOKSQe3bkj5V8TZOmPkIF0I+Q==,iv:bpXurkgitDpjj9d0KP1u5YMzdWNPTczRjyRN+0ekYp0=,tag:59V1etsp6DxS2zqXZlIJXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zu6n8h3re0ftq59w5ajp32xjz60m98q69eygqmp6v54hmrt289dqad9txh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV3gvN3pHcFZZamp2aE1v
            VCs2VXlDQUNBeWF3K25kVy9sY2I5TGtpRDBBClp4MGttMGg5K1MvWVd4enNXeC8v
            OFNWTTk2cldPa0UyM0tILzE5dUhZTGsKLS0tIGJwTlo2ckltRnVBY0Vua3F5UnE4
            cEI3VU9TbG5YZk4zMlM4TWg5bFFob0kKUWQ4ZCcf3xP5W4BZdStNjOfBWndHNh42
            t4PaedAw/FRQHPki8WzVISdxl+kYoPcvEZvYBksfznYvTP3VniWlkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T11:20:46Z"
    mac: ENC[AES256_GCM,data:NdqxFq6ECVxSMlt95vUdR1ZYJsnfvbvFoDY2BjHAM4gcCcRuXOSdQ+kDqRIQ0NhDz9YX4Cit6gS4C2UH0ADiFqw0GXAUQWw8PvSUZi5dSeT0nmLo4xg0Sw8s4pGCuHbl0hJspmFHuLVj2NRrYb57WeJTbB+Ws7Sdv20lFSpe/sk=,iv:fjgUcvEtto2VZmC8tY+I1XJGg8vRkMcIxuWU7NP5Sdg=,tag:+Igsru3B/MUc5jGr3+mycg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
